###
GET http://localhost:3001/api/users

###
DELETE http://localhost:3001/api/blogs/6094ca57f2bdae1a7452904b
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJpZCI6IjVlZTdiMDFkMDViZWFkNDYyNGRmZmY0NCIsImlhdCI6MTU5MjMyNTk5NX0.kXZNo93tmPd9Zo7DP6sw-KLzxbqd7Cdtyi3Ww2ho2t4

###
POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJpZCI6IjVlZTdiMDFkMDViZWFkNDYyNGRmZmY0NCIsImlhdCI6MTU5MjMyNTk5NX0.kXZNo93tmPd9Zo7DP6sw-KLzxbqd7Cdtyi3Ww2ho2t4

{   
    "title": "Blog Post for Deletion",
    "author": "Reynold",
    "url": "website.com",
    "likes": 1344232,
    "comments": []
}

###
POST http://localhost:3001/api/users
Content-Type: application/json

{   
    "username": "mule",
    "name": "hsmule",
    "password": "hbmule"
}

# USERS CREATED
# username: mule
# name: hsmule
# password: hbmule

# username: test
# name: Reynold
# password: svanhagen

###
PUT http://localhost:3001/api/blogs/5edc88069ddea21e00c92487
Content-Type: application/json

{   
    "title": "Second Blog Post",
    "author": "ReyDK",
    "url": "website.com",
    "likes": 32111
}

###
POST http://localhost:3001/api/login
Content-Type: application/json

{
    "username": "test",
    "password": "svanhagen"
}

###
POST http://localhost:3001/api/blogs/60b5f112b928712c4067b951/comments
Content-Type: application/json

{ 
    "comment": "Second comment"
}

